name: Build samples-test-spring
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    #if: ${{ false }}  # disable for now
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
      #Especifica java 8, con la version por defecto causa: Corrupted STDOUT by directly writing to native stream in forked JVM 1
      - name: Select Java Version
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - run: echo $GITHUB_WORKFLOW
      - run: echo $GITHUB_RUN_ID
      - run: echo $GITHUB_RUN_NUMBER
      - run: echo $GITHUB_JOB
      - run: echo $GITHUB_ACTION
      - run: echo $GITHUB_ACTIONS
      - run: echo $GITHUB_REPOSITORY
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REF_NAME
      - run: echo $GITHUB_ACTOR
      - run: echo $GITHUB_EVENT_NAME
      - run: echo $GITHUB_REF_PROTECTED	
      - run: echo $GITHUB_REF_TYPE

      #Para que falle el build per se ejecuten todas las fases de maven produciendo los reports
      #se configura maven para ignorar fallos y se anyade la action scacap/action-surefire-report@v1
      #que causara el fallo del build si ha fallado algun test
      #(similar comportamienta a cuando se usa junit reporter en jenkins)
      #Otra action similar que no solo muestra los resultados de los falloes es dorny/test-reporter@v1
      - name: Build and test
        run: mvn verify -Dmaven.test.failure.ignore=true -U --no-transfer-progress
      #- name: Generate surefire report
      #  if: always()
      #  uses: scacap/action-surefire-report@v1
      #  with:
      #    check_name: test-failure-report (ut, it)
      #    report_paths: '**/target/*-reports/TEST-*.xml'
      #    fail_on_test_failures: 'true'
 
      #Publica archivos de reports
      - if: always()
        name: Publish test report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/site/
      - if: always()
        name: Publish test reports for sonarqube job
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-for-sonar
          path: |
            target/surefire-reports/

